### ISSUE TITLE
Issues with overloaded functions

### ISSUE THREAD

**Issue by thatguypark** [ambrogio-dev/pg-compare#1]
Noticed that overloaded functions causes the script to end... :(

```
loading indexes success
loading functions error { [error: more than one function named "can_access_drawing"]
  name: 'error',
  length: 97,
  severity: 'ERROR',
  code: '42725',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'regproc.c',
  line: '148',
  routine: 'regprocin' }
load done
/*** Comparing terminated with errors ***/
```

Just putting it out there, if you want some help on this, let me know happy to join and contribute where I can.  :)

**Comment by thatguypark** [comment]
Sweet little tool though and very nicely done.

**Comment by alemar11** [comment]
Hey @thatguypark , sorry for the late answer.
Yes, we would love some help on this issue, thanks!

**Comment by rjjanuary** [comment]
I was going to report the issue, but someone already beat me to it.  Just wanted to +1 that this issue is preventing us from using it as well.  Otherwise it looks very complete and feature rich.  

I'm well versed in the RDBMS world, however new to both node and js.  I'd love to help out where I can.

**Comment by JerryMSunny** [comment]
@alemar11 Fixed this bug, Please merge the pull request.
