### ISSUE TITLE
loading functions error - is an aggregate function

### ISSUE THREAD

**Issue by julianopg** [ambrogio-dev/pg-compare#2]
Hi

I got the following error, could you help me, please?

```
loading functions error { [error: "array_cat_agg" is an aggregate function]
  name: 'error',
  length: 100,
  severity: 'ERROR',
  code: '42809',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'ruleutils.c',
  line: '1940',
  routine: 'pg_get_functiondef' }
load done
/*** Comparing terminated with errors ***/
```

One more thing, how can I compare all my schemas instead of the only one public schema?

**Comment by alemar11** [comment]
Hi @julianopg, can you give us more details? Thanks

**Comment by Stebluyk** [comment]
> One more thing, how can I compare all my schemas instead of the only one public schema?

Hi, i`m interested in this to

**Comment by alemar11** [comment]
> One more thing, how can I compare all my schemas instead of the only one public schema?

@JerryMSunny has added this functionality, please check version 0.2.0
